// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcju8H2WP-lwEGLyoPzWDS8dwtM8tVUhU',
    appId: '1:354591886485:web:1834e7463b0ea10c601f9c',
    messagingSenderId: '354591886485',
    projectId: 'messagenoti-c61df',
    authDomain: 'messagenoti-c61df.firebaseapp.com',
    storageBucket: 'messagenoti-c61df.appspot.com',
    measurementId: 'G-VLB53QQT9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ssncTMaf-GAdwXNEqeh3_LtU9fEjDi0',
    appId: '1:354591886485:android:c659924e4b0faad8601f9c',
    messagingSenderId: '354591886485',
    projectId: 'messagenoti-c61df',
    storageBucket: 'messagenoti-c61df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPgObvBblvlogPZ8MHZc7KY8EqYXBTsz4',
    appId: '1:354591886485:ios:14fb65c91aabc07f601f9c',
    messagingSenderId: '354591886485',
    projectId: 'messagenoti-c61df',
    storageBucket: 'messagenoti-c61df.appspot.com',
    iosBundleId: 'com.example.spacex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPgObvBblvlogPZ8MHZc7KY8EqYXBTsz4',
    appId: '1:354591886485:ios:0f50ede78b1c2a0f601f9c',
    messagingSenderId: '354591886485',
    projectId: 'messagenoti-c61df',
    storageBucket: 'messagenoti-c61df.appspot.com',
    iosBundleId: 'com.example.spacex.RunnerTests',
  );
}
